"""add image table

Revision ID: 063be12e6f5c
Revises: 26c096d99d3c
Create Date: 2024-07-08 15:26:27.615735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063be12e6f5c'
down_revision = '26c096d99d3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
