"""removed recipe instruction constraint

Revision ID: 26c096d99d3c
Revises: e09031046d0a
Create Date: 2024-07-03 14:03:59.363701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c096d99d3c'
down_revision = 'e09031046d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint('ck_recipes_instruction_length_under_two_hundred') 

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_check_constraint('ck_recipes_instruction_length_under_two_hundred', 'length(instruction)<200')
    # ### end Alembic commands ###
