"""added weight type column and validations

Revision ID: 84667b626df9
Revises: 073bffb66a2f
Create Date: 2024-06-28 10:16:44.818709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84667b626df9'
down_revision = '073bffb66a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight_type', sa.String()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_column('weight_type')

    # ### end Alembic commands ###
