"""add and fix serialized rules on all models, add category to dietary nos

Revision ID: e09031046d0a
Revises: f370daa507f2
Create Date: 2024-07-01 12:02:10.150843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e09031046d0a'
down_revision = 'f370daa507f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dietary_nos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dietary_nos', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
